### ISSUE TITLE
Split render/primary devices don't work properly

### ISSUE THREAD

**Issue by kujeger** [YaLTeR/niri#151]
Hi!

I run fedora on a m1 mac (fedora-asahi), and I wanted to try using the copr repository, but it seems it is only configured to create x86_64 builds. Would be nice if aarch64 could be added!

```
Repository 'fedora-39-aarch64' does not exist in project 'yalter/niri'.
Available repositories: 'fedora-rawhide-x86_64', 'fedora-39-x86_64'
```

Apologies if this repo is not the proper place to add it, but since it is mentioned in the README and the repo owner appears to both be `yalter` I hope it is :)

**Comment by YaLTeR** [comment]
Hey, that's pretty cool! I'll try enabling aarch64, idk if it builds or works there though

**Comment by kujeger** [comment]
Awesome! Niri builds and starts fine locally here, so hopefully it will work out of the box in copr!

**Comment by YaLTeR** [comment]
Well, it successfully built something. Could you try if it works?

**Comment by kujeger** [comment]
Installed, and works -- but only nested, not as full compositor, where there's just a black screen.
This also appears to be the case with a locally built one though, so I'd guess that has to do with the still-somewhat lacking GPU drivers for the M1.

I'd say this particular issue resolved, thanks a bunch! :tada:

**Comment by YaLTeR** [comment]
Hmm, I see, thanks for testing. I wonder if it would work fine on other aarch64 devices.

Are there any errors in the log when you try to run on a TTY?

**Comment by kujeger** [comment]
I'll test a bit more later today, I also have a pi4 and 5 I can test with when I get home

**Comment by YaLTeR** [comment]
Oh, that would be really nice!

**Comment by cmeissl** [comment]
> Hmm, I see, thanks for testing. I wonder if it would work fine on other aarch64 devices.
> 
> Are there any errors in the log when you try to run on a TTY?

I might be able to add a few things regarding this topic. smithay itself should work on aarch64 devices as I have
a compositor based on smithay running on an i.MX8M. But there are a few things notable.
First a lot of those devices have so called split kms where you have a separate drm node for the display engine
and another one for the gpu (not only a separate node, but really different hardware devices, in a lot of cases from different vendors). Support for that in mesa is a bit lacking and I was only able to make it work by directly specifying which nodes to use. Though things started to [improve](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24825) finally, so depending on the availability of that fix it might be easier. 

There is also `catacomb` compositor, which is also based on smithay and works on the PinePhone(Pro).

**Comment by YaLTeR** [comment]
> First a lot of those devices have so called split kms where you have a separate drm node for the display engine
and another one for the gpu

That's right, aren't M1 Macs exactly like that? Yeah, I'm not sure I can fix anything here without such a device to test it.

**Comment by kujeger** [comment]
I've tested and collected logs from pi4, pi5 and m1 now, but to summarize:
Nested works fine on all three.
Running from tty/login manager does not work on any of them.

starting niri on a pi4 (running latest fedora) gives this log, and also just crashes:
<details>
<summary>niri_pi4.log</summary>

```
2024-02-02T07:28:41.134414Z  INFO niri: starting version 0.1.0 (51243a0)
2024-02-02T07:28:41.188322Z DEBUG niri_config: loaded config from "/home/kujeger/.config/niri/config.kdl"
thread 'main' panicked at src/backend/tty.rs:203:22:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /builddir/build/BUILD/rustc-1.75.0-src/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /builddir/build/BUILD/rustc-1.75.0-src/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /builddir/build/BUILD/rustc-1.75.0-src/library/core/src/panicking.rs:127:5
   3: {closure#4}
   4: unwrap_or_else<(smithay::backend::drm::node::DrmNode, smithay::backend::drm::node::DrmNode), niri::backend::tty::{impl#0}::new::{closure_env#4}>
             at /builddir/build/BUILD/rustc-1.75.0-src/library/core/src/option.rs:976:21
   5: new
             at /builddir/build/BUILD/niri-51243a0a505a533057e7326fbbae882420f0d363/src/backend/tty.rs:198:14
   6: new
             at /builddir/build/BUILD/niri-51243a0a505a533057e7326fbbae882420f0d363/src/niri.rs:310:26
   7: main
             at /builddir/build/BUILD/niri-51243a0a505a533057e7326fbbae882420f0d363/src/main.rs:217:21
   8: call_once<fn() -> core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>, ()>
             at /builddir/build/BUILD/rustc-1.75.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

Starting on pi5 (running updated pi-os; fedora isn't quite runnable on the pi5 yet) and m1 (latest fedora) have essentially identical results. Niri starts, but produces no output. I can quit it normally doing super+shift+e  followed by <enter>
<details>
<summary>niri_pi5.log</summary>

```
2024-02-01T20:28:37.320781Z  INFO niri: starting version 0.1.0 (v0.1.0)
2024-02-01T20:28:37.362512Z DEBUG niri_config: loaded config from "/home/kujeger/.config/niri/config.kdl"
2024-02-01T20:28:37.515622Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
2024-02-01T20:28:37.543875Z DEBUG niri::backend::tty: device added: 57856 "/dev/dri/card0"
2024-02-01T20:28:37.544956Z  WARN niri::backend::tty: error adding device: DRM access error: Error loading resource handles on device `Some("/dev/dri/card0")` (Operation not supported (os error 95))

Caused by:
    Operation not supported (os error 95)
2024-02-01T20:28:37.544984Z DEBUG niri::backend::tty: device added: 57857 "/dev/dri/card1"
2024-02-01T20:28:37.846131Z DEBUG niri::backend::tty: device changed: 57857
2024-02-01T20:28:37.876112Z DEBUG niri::backend::tty: connecting connector: HDMI-A-1
2024-02-01T20:28:37.876121Z DEBUG niri::backend::tty: picking mode: Mode { name: "1024x600", clock: 50250, size: (1024, 600), hsync: (1068, 1156, 1344), vsync: (603, 609, 625), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
2024-02-01T20:28:37.890544Z DEBUG niri::niri: putting output HDMI-A-1 at x=0 y=0
2024-02-01T20:28:37.890613Z  INFO niri: listening on Wayland socket: wayland-2
2024-02-01T20:28:37.890623Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-2.9912.sock
2024-02-01T20:28:37.891230Z  WARN niri::backend::tty: no primary allocator
2024-02-01T20:28:37.891307Z  WARN niri::backend::tty: no primary allocator
2024-02-01T20:28:42.633527Z  WARN niri::backend::tty: no primary allocator
2024-02-01T20:28:43.201447Z  WARN niri::backend::tty: no primary allocator
2024-02-01T20:28:43.785463Z  WARN niri::backend::tty: no primary allocator
2024-02-01T20:28:43.891647Z DEBUG niri::watcher: exiting watcher thread for /home/kujeger/.config/niri/config.kdl
```
</details>
<details>
<summary>niri_m1.log</summary>

```
2024-02-01T19:25:25.827767Z  INFO niri: starting version 0.1.0 (51243a0)
2024-02-01T19:25:25.841911Z DEBUG niri_config: loaded config from "/home/kujeger/.config/niri/config.kdl"
2024-02-01T19:25:25.891721Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
2024-02-01T19:25:25.912506Z DEBUG niri::backend::tty: device added: 57858 "/dev/dri/card2"
2024-02-01T19:25:26.199986Z DEBUG niri::backend::tty: device changed: 57858
2024-02-01T19:25:26.200097Z DEBUG niri::backend::tty: connecting connector: eDP-1
2024-02-01T19:25:26.200103Z DEBUG niri::backend::tty: picking mode: Mode { name: "3024x1890", clock: 402278, size: (3024, 1890), hsync: (3032, 3064, 3104), vsync: (1992, 2074, 2160), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
2024-02-01T19:25:26.212194Z DEBUG niri::niri: putting output eDP-1 at x=0 y=0
2024-02-01T19:25:26.212240Z DEBUG niri::backend::tty: device added: 57857 "/dev/dri/card1"
2024-02-01T19:25:26.213380Z  WARN niri::backend::tty: error adding device: DRM access error: Error loading resource handles on device `Some("/dev/dri/card1")` (Operation not supported (os error 95))

Caused by:
    Operation not supported (os error 95)
2024-02-01T19:25:26.213404Z  INFO niri: listening on Wayland socket: wayland-1
2024-02-01T19:25:26.213408Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-1.56073.sock
2024-02-01T19:25:26.214561Z  WARN niri::backend::tty: no primary allocator
2024-02-01T19:25:26.215071Z  WARN niri::backend::tty: no primary allocator
2024-02-01T19:25:28.436218Z  WARN niri::backend::tty: no primary allocator
2024-02-01T19:25:28.840032Z  WARN niri::backend::tty: no primary allocator
2024-02-01T19:25:29.658992Z  WARN niri::backend::tty: no primary allocator
2024-02-01T19:25:29.714369Z DEBUG niri::watcher: exiting watcher thread for /home/kujeger/.config/niri/config.kdl
```
</details>

**Comment by cmeissl** [comment]
Just tried this out on a device which has kmsro. It won't work out of the box and specifying the primary gpu directly alone also does not fix it. But the reason is that niri will ignore the gpu if it does not represent the a render node. For kmsro devices this assumption is not correct and we will have to fix it. In the meantime this patch should make it work:

```patch
diff --git a/src/backend/tty.rs b/src/backend/tty.rs
index 474f12e..41740f1 100644
--- a/src/backend/tty.rs
+++ b/src/backend/tty.rs
@@ -1393,6 +1393,7 @@ fn primary_node_from_config(config: &Config) -> Option<(DrmNode, DrmNode)> {
                 }
             } else {
                 warn!("DRM node {path:?} is not a render node");
+                return Some((node, node));
             }
         }
         Err(err) => {

```

**Comment by kujeger** [comment]
Can confirm that applying that patch, plus manually specifying the device (`/dev/dri/card1`) worked on my pi5; cheers!

Haven't managed to get it working on the m1 though.

**Comment by nougatbyte** [comment]
I applied this patch and did a `cargo build --release`, copied the files again and edited the config to specify the gpu directly.
Sadly I still got the same error as mentioned here: https://github.com/YaLTeR/niri/issues/218#issuecomment-2020961687
I also tried /dev/dri/card0

Device is a Raspberry Pi Compute Module 4 (32GB Emmc, 8GB Ram, Raspberry Pi OS aarch64/bookworm)

**Comment by YaLTeR** [comment]
I just pushed 092420ec5a54f1cd5f4f59b75a60f5cfa7cceacd which includes a slightly modified patch from above (that avoids blackscreening desktop systems on misconfiguration) as well as a relaxed primary GPU check. I'd be very grateful if someone could test that:

1. Upstream niri now works with manually setting `render-drm-device` like with the patch above.
2. If it maybe now works even without manually setting `render-drm-device`?

**Comment by YaLTeR** [comment]
I'm getting reports that things now start up as they should (at least on RPI, M2 and even M1 MAX), so I'm closing this. For follow-up issues please open new ones.
