### ISSUE TITLE
Multimonitor not working

### ISSUE THREAD

**Issue by EdenQwQ** [YaLTeR/niri#194]
My secondary monitor (HDMI-A-1) won't work with the following config (while eDP-1 works fine):
```
output "HDMI-A-1" {
    scale 2.0
    transform "270"
    mode "1920x1080@60"
    position x=0 y=0
}

output "eDP-1" {
    scale 2.0
    transform "normal"
    mode "2240x1400@60"
    position x=540 y=0
}
```

Also, when I change `mode "1920x1080@60"` to `mode "1920x1080"`, niri would crash and won't start.

This is the output of `niri msg outputs`:
```
Output "HDMI-A-1" (2_26_10 -  - HDMI-A-1)
  Disabled
  Physical size: unknown
  Available modes:
    1920x1080@60.000
    1920x1080@60.000
    1920x1080@60.000
    1920x1080@59.940
    1920x1080@59.940
    1920x1080@60.000
    1920x1080@60.000
    1920x1080@59.940
    1920x1080@50.000
    1920x1080@50.000
    1920x1080@50.000
    1920x1080@50.000
    1680x1050@59.883
    1440x900@59.901
    1280x960@60.000
    1280x800@59.910
    1280x720@60.000
    1280x720@60.000
    1280x720@59.940
    1280x720@50.000
    1280x720@48.000
    1280x720@47.952
    1024x768@60.004
    800x600@60.317
    800x600@56.250
    640x480@60.000
    640x480@59.940

Output "eDP-1" (25_8_9 - 2650 - eDP-1)
  Current mode: 2240x1400 @ 60.002 Hz
  Physical size: 300x190 mm
  Available modes:
    2240x1400@60.002
    2240x1400@48.001
```

### System Information

* niri version: niri 0.1.1 (unknown commit)

* GPU: Intel Iris Xe

* CPU: Intel i5-12500H

**Comment by YaLTeR** [comment]
Uh huh. Could you please post the niri output? When running as a session, that's `journalctl --no-hostname -eb /usr/bin/niri > log`. Especially interested in when it crashed.

**Comment by EdenQwQ** [comment]
> Uh huh. Could you please post the niri output? When running as a session, that's `journalctl --no-hostname -eb /usr/bin/niri > log`. Especially interested in when it crashed.

This time the secondary monitor would display the default background for less than a second before niri crashes.
Here is the log:
```
Feb 14 23:18:16 niri[2649]: 2024-02-14T15:18:16.563928Z  INFO niri: starting version 0.1.1 (72c8f56)
Feb 14 23:18:16 niri[2649]: 2024-02-14T15:18:16.574368Z DEBUG niri_config: loaded config from "/home/eden/.config/niri/config.kdl"
Feb 14 23:18:16 niri[2649]: 2024-02-14T15:18:16.614034Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
Feb 14 23:18:16 niri[2649]: 2024-02-14T15:18:16.630289Z DEBUG niri::backend::tty: device added: 57857 "/dev/dri/card1"
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.090662Z DEBUG niri::backend::tty: this is the primary node
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.096257Z DEBUG niri::backend::tty: device changed: 57857
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.951173Z DEBUG niri::backend::tty: connecting connector: eDP-1
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.951190Z  WARN niri::backend::tty: configured mode 2240x1400@60 could not be found, falling back to preferred
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.951192Z DEBUG niri::backend::tty: picking mode: Mode { name: "2240x1400", clock: 212550, size: (2240, 1400), hsync: (2288, 2320, 2460), vsync: (1403, 1409, 1440), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.953230Z DEBUG niri::niri: putting output eDP-1 at x=540 y=0
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.953239Z DEBUG niri::backend::tty: connecting connector: HDMI-A-1
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.953241Z DEBUG niri::backend::tty: picking mode: Mode { name: "1920x1080", clock: 148500, size: (1920, 1080), hsync: (2008, 2052, 2200), vsync: (1084, 1089, 1125), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(DRIVER) }
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.954276Z DEBUG niri::niri: putting output HDMI-A-1 at x=0 y=0
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.954302Z  INFO niri: listening on Wayland socket: wayland-1
Feb 14 23:18:17 niri[2649]: 2024-02-14T15:18:17.954304Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-1.2649.sock
Feb 14 23:18:20 niri[2649]: thread 'main' panicked at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-server/src/lib.rs:123:5:
Feb 14 23:18:20 niri[2649]: called `Result::unwrap()` on an `Err` value: NulError(0, [0])
Feb 14 23:18:20 niri[2649]: stack backtrace:
Feb 14 23:18:20 niri[2649]:    0: rust_begin_unwind
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/rustc-1.75.0-src/library/std/src/panicking.rs:645:5
Feb 14 23:18:20 niri[2649]:    1: core::panicking::panic_fmt
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/rustc-1.75.0-src/library/core/src/panicking.rs:72:14
Feb 14 23:18:20 niri[2649]:    2: core::result::unwrap_failed
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/rustc-1.75.0-src/library/core/src/result.rs:1653:5
Feb 14 23:18:20 niri[2649]:    3: unwrap<alloc::ffi::c_str::CString, alloc::ffi::c_str::NulError>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/rustc-1.75.0-src/library/core/src/result.rs:1077:23
Feb 14 23:18:20 niri[2649]:    4: write_event
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-server/src/lib.rs:123:5
Feb 14 23:18:20 niri[2649]:    5: send_event<wayland_server::protocol::wl_output::WlOutput>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-server/src/display.rs:180:19
Feb 14 23:18:20 niri[2649]:    6: send_event
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-server/src/lib.rs:123:5
Feb 14 23:18:20 niri[2649]:    7: geometry
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-server/src/lib.rs:123:5
Feb 14 23:18:20 niri[2649]:    8: send_geometry_to
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/smithay/src/wayland/output/mod.rs:137:9
Feb 14 23:18:20 niri[2649]:    9: bind<niri::niri::State>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/smithay/src/wayland/output/handlers.rs:56:9
Feb 14 23:18:20 niri[2649]:   10: bind
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-server/src/global.rs:144:17
Feb 14 23:18:20 niri[2649]:   11: bind<wayland_server::protocol::wl_output::WlOutput, smithay::wayland::output::WlOutputData, niri::niri::State>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-server/src/global.rs:42:9
Feb 14 23:18:20 niri[2649]:   12: {closure#0}<niri::niri::State>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-backend/src/sys/server_impl/mod.rs:1361:24
Feb 14 23:18:20 niri[2649]:   13: with<(alloc::sync::Arc<std::sync::mutex::Mutex<(dyn wayland_backend::sys::server_impl::ErasedState + core::marker::Send)>, alloc::alloc::Global>, *mut core::ffi::c_void), wayland_backend::sys::server_impl::global_bind::{closure_env#0}<niri::niri::State>, ()>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/scoped-tls/src/lib.rs:171:13
Feb 14 23:18:20 niri[2649]:   14: global_bind<niri::niri::State>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-backend/src/sys/server_impl/mod.rs:1347:5
Feb 14 23:18:20 niri[2649]:   15: <unknown>
Feb 14 23:18:20 niri[2649]:   16: <unknown>
Feb 14 23:18:20 niri[2649]:   17: ffi_call
Feb 14 23:18:20 niri[2649]:   18: <unknown>
Feb 14 23:18:20 niri[2649]:   19: <unknown>
Feb 14 23:18:20 niri[2649]:   20: wl_event_loop_dispatch
Feb 14 23:18:20 niri[2649]:   21: {closure#0}<niri::niri::State>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-backend/src/sys/server_impl/mod.rs:410:13
Feb 14 23:18:20 niri[2649]:   22: set<(alloc::sync::Arc<std::sync::mutex::Mutex<(dyn wayland_backend::sys::server_impl::ErasedState + core::marker::Send)>, alloc::alloc::Global>, *mut core::ffi::c_void), wayland_backend::sys::server_impl::{impl#21}::dispatch_all_clients::{closure_env#0}<niri::niri::State>, i32>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/scoped-tls/src/lib.rs:137:9
Feb 14 23:18:20 niri[2649]:   23: dispatch_all_clients<niri::niri::State>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-backend/src/sys/server_impl/mod.rs:407:19
Feb 14 23:18:20 niri[2649]:   24: dispatch_all_clients<niri::niri::State>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-backend/src/sys/../server_api.rs:575:9
Feb 14 23:18:20 niri[2649]:   25: dispatch_clients<niri::niri::State>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/wayland-server/src/display.rs:59:22
Feb 14 23:18:20 niri[2649]:   26: {closure#13}
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/src/niri.rs:959:39
Feb 14 23:18:20 niri[2649]:   27: {closure#0}<niri::niri::State, calloop::sources::generic::Generic<wayland_server::display::Display<niri::niri::State>, std::io::error::Error>, niri::niri::{impl#2}::new::{closure_env#13}>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/calloop/src/sources/mod.rs:327:61
Feb 14 23:18:20 niri[2649]:   28: process_events<wayland_server::display::Display<niri::niri::State>, std::io::error::Error, calloop::sources::{impl#4}::process_events::{closure_env#0}<niri::niri::State, calloop::sources::generic::Generic<wayland_server::display::Display<niri::niri::State>, std::io::error::Error>, niri::niri::{impl#2}::new::{closure_env#13}>>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/calloop/src/sources/generic.rs:290:9
Feb 14 23:18:20 niri[2649]:   29: process_events<niri::niri::State, calloop::sources::generic::Generic<wayland_server::display::Display<niri::niri::State>, std::io::error::Error>, niri::niri::{impl#2}::new::{closure_env#13}>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/calloop/src/sources/mod.rs:326:9
Feb 14 23:18:20 niri[2649]:   30: dispatch_events<niri::niri::State>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/calloop/src/loop_logic.rs:445:31
Feb 14 23:18:20 niri[2649]:   31: dispatch<niri::niri::State, core::option::Option<core::time::Duration>>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/calloop/src/loop_logic.rs:559:9
Feb 14 23:18:20 niri[2649]:   32: run<niri::niri::State, niri::main::{closure_env#4}, core::option::Option<core::time::Duration>>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/vendor/calloop/src/loop_logic.rs:596:13
Feb 14 23:18:20 niri[2649]:   33: main
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/niri-0.1.1/src/main.rs:292:5
Feb 14 23:18:20 niri[2649]:   34: call_once<fn() -> core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>, ()>
Feb 14 23:18:20 niri[2649]:              at /builddir/build/BUILD/rustc-1.75.0-src/library/core/src/ops/function.rs:250:5
Feb 14 23:18:20 niri[2649]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Feb 14 23:18:20 niri[2649]: 2024-02-14T15:18:20.491279Z DEBUG niri::watcher: exiting watcher thread for /home/eden/.config/niri/config.kdl
```

**Comment by YaLTeR** [comment]
wtf lol, I guess the edid results for a monitor contain a null byte? I'll add a check

**Comment by EdenQwQ** [comment]
> wtf lol, I guess the edid results for a monitor contain a null byte? I'll add a check

Could it be related to unknown physical size of the monitor (as in the output of `niri msg outputs`)?
I have no knowledge about this. Please take your time.

**Comment by YaLTeR** [comment]
Could you try again with the latest git commit? It should fix the crashes at least.

**Comment by EdenQwQ** [comment]
> Could you try again with the latest git commit? It should fix the crashes at least.

It is working flawlessly now when I use `mode "1920x1080"`. Yet HDMI-A-1 would be disabled when I use `mode "1920x1080@60.000`.

**Comment by YaLTeR** [comment]
Could you post a log when it's disabled? I'm not sure why there's so many matching modes, might be picking the "wrong one".

**Comment by EdenQwQ** [comment]
I'm not able to get a log but here is the output of the `niri` command:
```
2024-02-14T16:40:22.188229Z  INFO niri: starting version 0.1.1 (unknown commit)
2024-02-14T16:40:22.198530Z DEBUG niri_config: loaded config from "/home/eden/.config/niri/config.kdl"
2024-02-14T16:40:22.272040Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
2024-02-14T16:40:22.288930Z DEBUG niri::backend::tty: device added: 57856 "/dev/dri/card0"
2024-02-14T16:40:22.671076Z DEBUG niri::backend::tty: this is the primary node
2024-02-14T16:40:22.677833Z DEBUG niri::backend::tty: device changed: 57856
2024-02-14T16:40:23.517794Z DEBUG niri::backend::tty: connecting connector: eDP-1
2024-02-14T16:40:23.517844Z  WARN niri::backend::tty: configured mode 2240x1400@60 could not be found, falling back to preferred
2024-02-14T16:40:23.517847Z DEBUG niri::backend::tty: picking mode: Mode { name: "2240x1400", clock: 212550, size: (2240, 1400), hsync: (2288, 2320, 2460), vsync: (1403, 1409, 1440), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
2024-02-14T16:40:23.520036Z DEBUG niri::niri: putting output eDP-1 at x=540 y=0
2024-02-14T16:40:23.520050Z DEBUG niri::backend::tty: connecting connector: HDMI-A-1
2024-02-14T16:40:23.520058Z DEBUG niri::backend::tty: picking mode: Mode { name: "1920x1080i", clock: 74250, size: (1920, 1080), hsync: (2008, 2052, 2200), vsync: (1084, 1094, 1125), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(DRIVER) }
2024-02-14T16:40:23.522171Z  WARN niri::backend::tty: error connecting connector: The underlying drm surface encountered an error: DRM access error: Error testing state on device `Some("/dev/dri/card0")` (Invalid argument (os error 22))

Caused by:
    0: DRM access error: Error testing state on device `Some("/dev/dri/card0")` (Invalid argument (os error 22))
    1: Invalid argument (os error 22)
2024-02-14T16:40:23.522208Z  INFO niri: listening on Wayland socket: wayland-1
2024-02-14T16:40:23.522212Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-1.121271.sock
2024-02-14T16:40:29.002140Z ERROR niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card0")` (Permission denied (os error 13))
2024-02-14T16:40:29.002415Z DEBUG niri::backend::tty: pausing session
2024-02-14T16:40:29.005412Z  WARN niri::backend::tty: device is inactive
2024-02-14T16:40:29.016572Z  WARN niri::backend::tty: device is inactive
```

**Comment by YaLTeR** [comment]
I see, looks like it tried picking an interlaced mode and failed. I'll need to check what other compositors do, maybe just filter those out.

**Comment by YaLTeR** [comment]
Could you once again try the latest git? I pushed a commit that filters out interlaced modes.

wlroots seems to filter them too: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/feb54979c0940655e36119c63e18a9ee72cc03b0/backend/drm/drm.c#L1461

**Comment by EdenQwQ** [comment]
> Could you once again try the latest git? I pushed a commit that filters out interlaced modes.
> 
> wlroots seems to filter them too: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/feb54979c0940655e36119c63e18a9ee72cc03b0/backend/drm/drm.c#L1461

That fixed the issue. Everything is working fine now!

**Comment by YaLTeR** [comment]
Thanks for testing! Glad we got this fixed, sounds like a somewhat usual monitor, by today's standards at least.
