### ISSUE TITLE
software renderer

### ISSUE THREAD

**Issue by LukIsHere** [YaLTeR/niri#218]
i run linux (debian trixie) on old chromebook with no gpu drivers since there are no availble atm and probably never will
that's why for rendering graphics on it i use software renderer
most wayland window menagers (sawy or gnome/mutter) work on it without any issue
but niri doesn't really want to
when i try to run it says

2024-02-2016:56:57.0833562
INFO niri: starting version 0.1.2 (unknown commit)
2024-02-2016:56:57.1500902 DEBUG niri _config: loaded config from "/home/linux/.config/niri/config-kd1"
thread
'main'
panicked at src/main.rs: 162:6:
called
Result:: unwrap()
value: error initializing the TTY backend
Caused by:
error getting the render node for the primary GPU
stack backtrace:
0: rust_begin_unwind
at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
1: core:: panicking:: panic_fmt
at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking-rs:72:14
2: core: result::unwrap_failed
at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
3: unwrap‹niri::niri::State, alloc:: boxed: :Box‹dyn core::error::Error, alloc::alloc::Global>
at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
at /home/linux/Pobrane/niri-0.1.2/src/main.rs: 156:21
5: call_once<fn()
→> core::result: :Result‹(), alloc: :boxed: :Box‹dyn core::error::Error, alloc::alloc::Global», (› at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with 'RUST_BACKTRACE=full for a verbose backtrace.

my guess is that it either doesn't have software rendering support
or it is not enabled. i tried going through options and couldn't find anything. So my question is is there an option to enable it or there is no support yet or not planned at all (something like pixman)?

### System Information

* niri version: niri 0.1.2 (unknown commit)

* GPU: PowerVR GX6250 (no driver)

* CPU: MediaTek MT8173

**Comment by YaLTeR** [comment]
There's no software rendering support at the moment. I'm also not sure Smithay fully supports pixman for regular rendering at the moment (cc @cmeissl); but even if it does, this would require somewhat awkward refactors in niri, since we currently store GL textures directly in a few places which simplifies the logic.

**Comment by cmeissl** [comment]
It does, see: https://github.com/Smithay/smithay/pull/1228
It should work with gbm and also with dumb buffers (tested during development by replacing multigpu renderer with `PixmanRenderer`) . What we lack is an easy way to dynamically select a renderer, multigpu makes it even more complicated.

**Comment by mia0x75** [comment]
+1

**Comment by LukIsHere** [comment]
> GPU Mali G31


as far as i know ur cpu has open [source drivers](https://docs.mesa3d.org/drivers/panfrost.html) in mesa for opengl 3.1

so your issue might not be related to lack of software renderer in niri

**Comment by nougatbyte** [comment]
I get the same error as mia0x75 on a Raspberry Pi Compute Module 4 with current RaspberryPi OS (Bookworm).
If I start gnome first and start niri inside a window it is working without problems.

But if I try to start niri from gdm3 it fails:
[error.log](https://github.com/YaLTeR/niri/files/14761769/error.log)

GLXInfo suggests my GPU drivers are there:
[glxinfo.log](https://github.com/YaLTeR/niri/files/14761768/glxinfo.log)

Can someone enlighten me please? Should I run a minimal WM around niri as a workaround?

**Comment by YaLTeR** [comment]
@nougatbyte you're hitting #151

**Comment by YaLTeR** [comment]
Actually, looking at the backtraces, everyone here is hitting #151. So while a software renderer would potentially be cool, the solution should be much simpler (fixing #151).

**Comment by YaLTeR** [comment]
@LukIsHere could you please check if 092420ec5a54f1cd5f4f59b75a60f5cfa7cceacd fixes it for you?

**Comment by LukIsHere** [comment]
https://github.com/YaLTeR/niri/assets/92756992/d272c8f7-c9b2-4089-8e28-e7fbe346e548
i compiled latest version of main branch
and got a black screen, so unless someone introduced it in other commit nope
still broken

**Comment by YaLTeR** [comment]
Okay, I think this means that the relaxed check worked as intended (instead of a panic, it tried to proceed, but the node was wrong). To exit the black screen, you could try Super+Shift+E followed by Enter.

Could you paste the output of `ls /dev/dri/` and also try setting [render-drm-device](https://github.com/YaLTeR/niri/wiki/Configuration:-Debug-Options#render-drm-device) to the render or card devices there to see if one will work? Also, you can run in tmux to be able to see the output afterwards (might need a screen refresh when on a TTY to see the real output).

**Comment by LukIsHere** [comment]
> ls /dev/dri
outputs
```by-path card0```
can be seen on picture


adding
```
debug {
  render-drm-device "/dev/dri/card0"
}
```
to 
> ~/.config/niri/config.kdl
doesn't fix the issue

**Comment by LukIsHere** [comment]
forgot to include the picture
![image](https://github.com/YaLTeR/niri/assets/92756992/d579262e-b1b0-448f-97fa-b0174965a28f)
sorry for markdown mess in reply
there is no preview in mobile github so i write it blindly

**Comment by nougatbyte** [comment]
For me its fixed on main branch on Raspberry Pi Compute module 4

**Comment by YaLTeR** [comment]
@LukIsHere thank you for testing. I'm assuming that in your case, the problem is indeed that there's no OpenGL support, and a software renderer would be needed.

@nougatbyte cool! Do you still need to set `render-drm-device` manually for it to work?

**Comment by bill88t** [comment]
Hello! I'm also trying to get a machine without a GPU going with niri.

I've added:
```
debug {
  render-drm-device "/dev/dri/card0"
}
```
as the system shows:
```
[bill88t@funsized | ~]> ls /dev/dri/
by-path  card0
[bill88t@funsized | ~]> ls /dev/dri/by-path/
platform-simple-framebuffer.0-card
[bill88t@funsized | ~]>
```
But all I get, regardless of launch method (cosmic-greeter, lightdm, tty) is the common "black screen", where nothing renders.
Arch Linux ARM (BredOS), niri version `25.11-1`

![Image](https://github.com/user-attachments/assets/564850bc-9143-447c-9ec9-120cb7be4794)

I'm using a config from another system, with the debug renderer modification.
I'd be happy to rebuild if software rendering is under an option or a patch needs testing.

**Comment by bill88t** [comment]
Patch soon.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/b2f600f5-42ab-44e4-a0ad-c41c4c73d455" />

**Comment by mnlipp** [comment]
I just wanted to test niri and failed, most likely due to this issue (well, I'm sure that I don't have hardware acceleration in my VM -- never needed it with gnome -- and I hope it will be the only problem).

I became aware of niri by a recently published article in a German computer magazine (https://www.heise.de/ratgeber/Minimalistischer-Linux-Desktop-Der-Tiling-Wayland-Compositor-Niri-im-Test-11229666.html). I assume others might give it a try as well when reading this article. As it praises niri quite heavily, the current situation is rather disappointing.

As there seems to be a solution, it might be worth it to prioritize the review of the PR (only suggesting).
