### ISSUE TITLE
niri panics when launched through tty

### ISSUE THREAD

**Issue by metent** [YaLTeR/niri#239]
Log:

```
2024-03-03T14:41:51.478471Z  INFO niri: starting version 0.1.2 (v0.1.2-65-gc4145b0)
2024-03-03T14:41:51.781979Z DEBUG niri_config: loaded config from "/home/rishabh/.config/niri/config.kdl"
2024-03-03T14:41:52.061351Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
2024-03-03T14:41:52.092054Z DEBUG niri::backend::tty: device added: 57857 "/dev/dri/card1"
2024-03-03T14:41:52.556175Z DEBUG niri::backend::tty: this is the primary node
2024-03-03T14:41:52.568434Z DEBUG niri::backend::tty: device changed: 57857
2024-03-03T14:41:53.749522Z DEBUG niri::backend::tty: connecting connector: eDP-1
2024-03-03T14:41:53.749639Z DEBUG niri::backend::tty: picking mode: Mode { name: "1440x900", clock: 88890, size: (1440, 900), hsync: (1488, 1520, 1600), vsync: (903, 909, 926), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
```

Stack trace:

```
thread 'main' panicked at /home/rishabh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/edid-rs-0.1.0/src/lib.rs:641:13:
attempt to subtract with overflow
stack backtrace:
   0:     0x5d16679cb78c - std::backtrace_rs::backtrace::libunwind::trace::ha69d38c49f1bf263
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5d16679cb78c - std::backtrace_rs::backtrace::trace_unsynchronized::h93125d0b85fd543c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5d16679cb78c - std::sys_common::backtrace::_print_fmt::h8d65f438e8343444
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5d16679cb78c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41751d2af6c8033a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5d16679fba2c - core::fmt::rt::Argument::fmt::h5db2f552d8a28f63
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
   5:     0x5d16679fba2c - core::fmt::write::h99465148a27e4883
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
   6:     0x5d16679c755e - std::io::Write::write_fmt::hee8dfd57bd179ab2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
   7:     0x5d16679cb574 - std::sys_common::backtrace::_print::h019a3cee3e814da4
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5d16679cb574 - std::sys_common::backtrace::print::h55694121c2ddf918
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5d16679cd633 - std::panicking::default_hook::{{closure}}::h29cbe3da3891b0b0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
  10:     0x5d16679cd354 - std::panicking::default_hook::h881e76b2b8c74280
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
  11:     0x5d16679cdbb5 - std::panicking::rust_panic_with_hook::hcc36e25b6e33969c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:731:13
  12:     0x5d16679cda66 - std::panicking::begin_panic_handler::{{closure}}::ha415efb0f69f41f9
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:601:13
  13:     0x5d16679cbcb6 - std::sys_common::backtrace::__rust_end_short_backtrace::h395fe90f99451e4e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5d16679cd802 - rust_begin_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
  15:     0x5d1665c81685 - core::panicking::panic_fmt::h452a83e54ecd764e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
  16:     0x5d1665c81723 - core::panicking::panic::h440670b29ba8362f
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
  17:     0x5d1666ac9a41 - edid_rs::DetailedTiming::parse::h61f6ce1097c10d25
                               at /home/rishabh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/edid-rs-0.1.0/src/lib.rs:641:13
  18:     0x5d1666aca957 - edid_rs::MonitorDescriptors::parse::h6c5835741479f86e
                               at /home/rishabh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/edid-rs-0.1.0/src/lib.rs:777:35
  19:     0x5d1666ac6844 - edid_rs::EDID::parse::hc985ce5a2eba621f
                               at /home/rishabh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/edid-rs-0.1.0/src/lib.rs:138:84
  20:     0x5d1665f7dd98 - edid_rs::parse::h63ada106120f50f9
                               at /home/rishabh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/edid-rs-0.1.0/src/lib.rs:975:5
  21:     0x5d1665e9d268 - smithay_drm_extras::edid::get_edid::h1805e54db8ede8e5
                               at /home/rishabh/.cargo/git/checkouts/smithay-b5a338d5236320f6/8924f6c/smithay-drm-extras/src/edid.rs:60:5
  22:     0x5d1665e9cd33 - smithay_drm_extras::edid::EdidInfo::for_connector::{{closure}}::h70f0a3ce92a70b31
                               at /home/rishabh/.cargo/git/checkouts/smithay-b5a338d5236320f6/8924f6c/smithay-drm-extras/src/edid.rs:37:31
  23:     0x5d1665e44cb9 - core::option::Option<T>::and_then::hdb9c1506cf7a9164
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/option.rs:1414:24
  24:     0x5d1665e9ccf1 - smithay_drm_extras::edid::EdidInfo::for_connector::h8cefc972569887e3
                               at /home/rishabh/.cargo/git/checkouts/smithay-b5a338d5236320f6/8924f6c/smithay-drm-extras/src/edid.rs:34:9
  25:     0x5d1666116eca - niri::backend::tty::Tty::connector_connected::h0bf586bcba8b6d54
                               at /home/rishabh/software/niri/src/backend/tty.rs:707:29
  26:     0x5d1666112086 - niri::backend::tty::Tty::device_changed::h3f61492f77de10c6
                               at /home/rishabh/software/niri/src/backend/tty.rs:534:39
  27:     0x5d1666110cf6 - niri::backend::tty::Tty::device_added::h92625e0627f25a53
                               at /home/rishabh/software/niri/src/backend/tty.rs:510:9
  28:     0x5d1666109fd2 - niri::backend::tty::Tty::init::h5ea283a2c5f41a8e
                               at /home/rishabh/software/niri/src/backend/tty.rs:286:31
  29:     0x5d1666139ff6 - niri::backend::Backend::init::h097b8b5889792861
                               at /home/rishabh/software/niri/src/backend/mod.rs:39:34
  30:     0x5d1665e71ce9 - niri::niri::State::new::h9b003c359437a8b7
                               at /home/rishabh/software/niri/src/niri.rs:342:9
  31:     0x5d1665c8bad8 - niri::main::h5b36c9826f6f0f2c
                               at /home/rishabh/software/niri/src/main.rs:171:21
  32:     0x5d1665cad3bb - core::ops::function::FnOnce::call_once::hdb6e86116d1d6e30
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  33:     0x5d1665c95ede - std::sys_common::backtrace::__rust_begin_short_backtrace::h0acd20ab788c6785
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
  34:     0x5d1665c9bb51 - std::rt::lang_start::{{closure}}::h711dafaf313f2523
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:166:18
  35:     0x5d16679bfd4b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h14c5f6d1cd70a60f
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:284:13
  36:     0x5d16679bfd4b - std::panicking::try::do_call::h2d02374ca451446a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  37:     0x5d16679bfd4b - std::panicking::try::h9f7922394bf57392
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  38:     0x5d16679bfd4b - std::panic::catch_unwind::ha1600f9dd4ee7270
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  39:     0x5d16679bfd4b - std::rt::lang_start_internal::{{closure}}::hfbd80e7d681b21a1
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:48
  40:     0x5d16679bfd4b - std::panicking::try::do_call::heacaa33dbdaa16e0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  41:     0x5d16679bfd4b - std::panicking::try::h637875f7c9db85ea
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  42:     0x5d16679bfd4b - std::panic::catch_unwind::h4caa9c0c78cb4c19
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  43:     0x5d16679bfd4b - std::rt::lang_start_internal::h2d6a60ec944b523d
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:20
  44:     0x5d1665c9bb2a - std::rt::lang_start::h6c0fc616df57d3d5
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:165:17
  45:     0x5d1665c8fdde - main
  46:     0x7fdc0ac76cd0 - <unknown>
  47:     0x7fdc0ac76d8a - __libc_start_main
  48:     0x5d1665c81f55 - _start
  49:                0x0 - <unknown>
```

### System Information

* niri version: niri 0.1.2 (v0.1.2-65-gc4145b0)

* GPU: Intel HD Graphics 6000

* CPU: Intel(R) Core(TM) i5-5350U (4) @ 2.90 GHz

**Comment by YaLTeR** [comment]
Wow that's fun. Thanks for the report, looks like a bug in edid-rs.

**Comment by YaLTeR** [comment]
Could you try if 2750b20 fixes it?

**Comment by YaLTeR** [comment]
Could you try if 2750b20 fixes it?

**Comment by metent** [comment]
> Could you try if [2750b20](https://github.com/YaLTeR/niri/commit/2750b2038bed5495bcdfeacc7be25267d15ceab1) fixes it?

Yup, this resolves the issue. Thanks for the quick fix! May I ask what is the package `edid-rs` used for?

**Comment by YaLTeR** [comment]
It's used for getting some monitor info (model, make, name). Although to be fair edid-rs is pretty bad at parsing EDIDs seen in the wild, and work is underway to replace it with the much more mature libdisplay-info, so I just added a quick workaround.
