### ISSUE TITLE
kitty crashes when passed an invalid XDG_ACTIVATION_TOKEN

### ISSUE THREAD

**Issue by notpeelz** [YaLTeR/niri#330]
I'm testing niri as a nested compositor under sway.
I ran kitty from a VS Code integrated terminal, which caused it to crash instantly. Turns out VS Code pollutes the terminal environment with env vars inherited from chromium/electron (yay...)

Specifically, kitty crashes under niri if `XDG_ACTIVATION_TOKEN=` is set to an invalid token:
```
export XDG_ACTIVATION_TOKEN=xyz
unset DISPLAY
export WAYLAND_DISPLAY=wayland-2
kitty
```

I don't know if this is a bug in kitty, niri or smithay. All I know is that I can't reproduce it under sway.

### Kitty backtrace

```
#0  wl_proxy_get_version (proxy=proxy@entry=0x0) at ../wayland-1.22.0/src/wayland-client.c:2248
#1  0x000074fc5af0cd77 in xdg_activation_v1_activate (surface=0x5a81019c5360, token=0x74fc5af90178 "xyz", xdg_activation_v1=0x0)
    at glfw/wayland-xdg-activation-v1-client-protocol.h:235
#2  glfwWaylandActivateWindow (activation_token=0x74fc5af90178 "xyz", handle=<optimized out>) at glfw/wl_window.c:2286
#3  glfwWaylandActivateWindow (handle=<optimized out>, activation_token=0x74fc5af90178 "xyz") at glfw/wl_window.c:2283
#4  0x000074fc5be7ae29 in focus_os_window (w=<optimized out>, activation_token=<optimized out>, also_raise=<optimized out>) at kitty/glfw.c:1335
#5  pyfocus_os_window (self=<optimized out>, args=<optimized out>) at kitty/state.c:864
#6  0x000074fc5d1a52ed in cfunction_call (func=0x74fc5c4cddf0, args=0x74fc5b3d0f00, kwargs=0x0) at Objects/methodobject.c:548
#7  0x000074fc5d18550b in _PyObject_MakeTpCall (tstate=0x74fc5d622ae8 <_PyRuntime+459656>, callable=0x74fc5c4cddf0, args=<optimized out>, nargs=0x3, 
    keywords=0x0) at Objects/call.c:240
#8  0x000074fc5d08bdfa in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x74fc5d6df688, throwflag=<optimized out>) at Python/bytecodes.c:2706
#9  0x000074fc5d187f70 in _PyEval_EvalFrame (throwflag=0x0, frame=0x74fc5d6df408, tstate=0x74fc5d622ae8 <_PyRuntime+459656>)
    at ./Include/internal/pycore_ceval.h:89
#10 _PyEval_Vector (kwnames=0x0, argcount=0x4, args=0x7ffc50dfecc0, locals=0x0, func=0x74fc5b116b60, tstate=0x74fc5d622ae8 <_PyRuntime+459656>)
    at Python/ceval.c:1683
#11 _PyFunction_Vectorcall (kwnames=0x0, nargsf=<optimized out>, stack=0x7ffc50dfecc0, func=0x74fc5b116b60) at Objects/call.c:419
#12 _PyObject_FastCallDictTstate (tstate=<optimized out>, callable=0x74fc5b116b60, args=0x7ffc50dfecc0, nargsf=<optimized out>, kwargs=<optimized out>)
    at Objects/call.c:133
#13 0x000074fc5d1b4dfd in _PyObject_Call_Prepend (tstate=0x74fc5d622ae8 <_PyRuntime+459656>, callable=0x74fc5b116b60, obj=0x74fc5c46cbf0, args=<optimized out>, 
    kwargs=0x0) at Objects/call.c:508
#14 0x000074fc5d285aa4 in slot_tp_call (self=0x74fc5c46cbf0, args=0x74fc5af74680, kwds=0x0) at Objects/typeobject.c:8770
#15 0x000074fc5d18550b in _PyObject_MakeTpCall (tstate=0x74fc5d622ae8 <_PyRuntime+459656>, callable=0x74fc5c46cbf0, args=<optimized out>, nargs=0x3, 
    keywords=0x0) at Objects/call.c:240
#16 0x000074fc5d08bdfa in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x74fc5d6df320, throwflag=<optimized out>) at Python/bytecodes.c:2706
#17 0x000074fc5d23d767 in PyEval_EvalCode (co=0x74fc5cc78e40, globals=<optimized out>, locals=0x74fc5cd2e300) at Python/ceval.c:578
#18 0x000074fc5d257a15 in builtin_exec_impl (module=<optimized out>, closure=<optimized out>, locals=0x74fc5cd2e300, globals=0x74fc5cd2e300, 
    source=0x74fc5cc78e40) at Python/bltinmodule.c:1096
#19 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/clinic/bltinmodule.c.h:586
#20 0x000074fc5d19a98e in cfunction_vectorcall_FASTCALL_KEYWORDS (func=<optimized out>, args=0x74fc5d6df180, nargsf=<optimized out>, kwnames=0x0)
    at Objects/methodobject.c:438
#21 0x000074fc5d19a844 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=0x8000000000000002, args=0x74fc5d6df180, callable=0x74fc5ccc9e40, 
    tstate=0x74fc5d622ae8 <_PyRuntime+459656>) at ./Include/internal/pycore_call.h:92
#22 PyObject_Vectorcall (callable=0x74fc5ccc9e40, args=0x74fc5d6df180, nargsf=0x8000000000000002, kwnames=0x0) at Objects/call.c:325
#23 0x000074fc5d08bdfa in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x74fc5d6df0d8, throwflag=<optimized out>) at Python/bytecodes.c:2706
#24 0x000074fc5d26d2fe in pymain_run_module (modname=modname@entry=0x74fc5d310088 L"__main__", set_argv0=set_argv0@entry=0x0) at Modules/main.c:300
#25 0x000074fc5d0cc20b in pymain_run_python (exitcode=0x7ffc50dff334) at Modules/main.c:626
#26 Py_RunMain () at Modules/main.c:709
#27 0x00005a8100932628 in run_embedded (run_data=<synthetic pointer>) at kitty/launcher/main.c:215
#28 main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at kitty/launcher/main.c:383
```

### System Information
* niri version: niri 0.1.5 (unknown commit)
* kitty version: 0.33.1 (yes it's outdated, blame the Arch package maintainer)
* Distro: Arch Linux
* GPU: AMD Radeon RX 6900 XT
* CPU: AMD Ryzen 9 3900X

**Comment by YaLTeR** [comment]
niri doesn't implement xdg-activation (yet) and kitty (through glfw) is trying to use it, leading to the crash. This is a bug in kitty, or rather probably in glfw. Either way, niri will support xdg-activation eventually.
