### ISSUE TITLE
Niri crashes when resuming from S3 sleep

### ISSUE THREAD

**Issue by robbins** [YaLTeR/niri#509]
After suspending the system with `systemctl suspend` and resuming it with a keypress, Niri displays on the screen for a brief instant and then crashes, going back to a TTY.

### System Information

* niri version: niri stable 0.1.7
I'm using niri-flake at this rev: https://github.com/sodiboo/niri-flake/tree/38186d3da0497d14404980289c5515d828b78edc which pulls Niri at this rev: https://github.com/YaLTeR/niri/tree/e7c201abba6fedaa57001639810af3b6bd9b852e

* Distro: NixOS Unstable

* GPU: AMD RX 570 8GB

* CPU: AMD Ryzen 9 7900X

Journald output: https://pastebin.com/P0RuHvNd

**Comment by YaLTeR** [comment]
The crash from that log:
```
Jul 02 16:40:03 hostname niri[3462]: 2024-07-02T20:40:03.125560Z DEBUG niri::backend::tty: device changed: 57857  
Jul 02 16:40:03 hostname niri[3462]: thread 'main' panicked at /smithay-234586d/smithay-drm-extras/src/drm_scanner/connector_scanner.rs:37:50:  
Jul 02 16:40:03 hostname niri[3462]: called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }  
Jul 02 16:40:03 hostname niri[3462]: stack backtrace:  
Jul 02 16:40:03 hostname niri[3462]:    0: rust_begin_unwind  
Jul 02 16:40:03 hostname niri[3462]:    1: core::panicking::panic_fmt  
Jul 02 16:40:03 hostname niri[3462]:    2: core::result::unwrap_failed  
Jul 02 16:40:03 hostname niri[3462]:    3: unwrap<drm::control::ResourceHandles, std::io::error::Error>  
Jul 02 16:40:03 hostname niri[3462]:              at /rustc-1.78.0-src/library/core/src/result.rs:1077:23  
Jul 02 16:40:03 hostname niri[3462]:    4: scan<smithay::backend::drm::device::DrmDevice>  
Jul 02 16:40:03 hostname niri[3462]:              at /smithay-234586d/smithay-drm-extras/src/drm_scanner/connector_scanner.rs:37:27  
Jul 02 16:40:03 hostname niri[3462]:    5: scan_connectors<smithay_drm_extras::drm_scanner::crtc_mapper::SimpleCrtcMapper, smithay::backend::drm::device::DrmDevice>  
Jul 02 16:40:03 hostname niri[3462]:              at /smithay-234586d/smithay-drm-extras/src/drm_scanner.rs:108:20  
Jul 02 16:40:03 hostname niri[3462]:    6: device_changed  
Jul 02 16:40:03 hostname niri[3462]:              at ./src/backend/tty.rs:602:22  
Jul 02 16:40:03 hostname niri[3462]:    7: on_udev_event  
Jul 02 16:40:03 hostname niri[3462]:              at ./src/backend/tty.rs:334:17  
Jul 02 16:40:03 hostname niri[3462]:    8: {closure#0}  
Jul 02 16:40:03 hostname niri[3462]:              at ./src/backend/tty.rs:215:13  
Jul 02 16:40:03 hostname niri[3462]:    9: {closure#0}<niri::niri::State, smithay::backend::udev::UdevBackend, niri::backend::tty::{impl#1}::new::{closure_env#0}>  
Jul 02 16:40:03 hostname niri[3462]:              at /calloop-0.14.0/src/sources/mod.rs:327:61  
Jul 02 16:40:03 hostname niri[3462]:   10: process_events<calloop::sources::{impl#4}::process_events::{closure_env#0}<niri::niri::State, smithay::backend::udev::UdevBackend, niri::backend::tty::{impl#1}::new::{closure_env#0}>>  
Jul 02 16:40:03 hostname niri[3462]:              at /smithay-234586d/src/backend/udev.rs:184:29  
Jul 02 16:40:03 hostname niri[3462]:   11: process_events<niri::niri::State, smithay::backend::udev::UdevBackend, niri::backend::tty::{impl#1}::new::{closure_env#0}>  
Jul 02 16:40:03 hostname niri[3462]:              at /calloop-0.14.0/src/sources/mod.rs:326:9  
Jul 02 16:40:03 hostname niri[3462]:   12: dispatch_events<niri::niri::State>  
Jul 02 16:40:03 hostname niri[3462]:              at /calloop-0.14.0/src/loop_logic.rs:445:31  
Jul 02 16:40:03 hostname niri[3462]:   13: dispatch<niri::niri::State, core::option::Option<core::time::Duration>>  
Jul 02 16:40:03 hostname niri[3462]:              at /calloop-0.14.0/src/loop_logic.rs:559:9  
Jul 02 16:40:03 hostname niri[3462]:   14: run<niri::niri::State, niri::main::{closure_env#4}, core::option::Option<core::time::Duration>>  
Jul 02 16:40:03 hostname niri[3462]:              at /calloop-0.14.0/src/loop_logic.rs:596:13  
Jul 02 16:40:03 hostname niri[3462]:   15: main  
Jul 02 16:40:03 hostname niri[3462]:              at ./src/main.rs:264:5  
Jul 02 16:40:03 hostname niri[3462]:   16: call_once<fn() -> core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>, ()>  
Jul 02 16:40:03 hostname niri[3462]:              at /rustc-1.78.0-src/library/core/src/ops/function.rs:250:5  
Jul 02 16:40:03 hostname niri[3462]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Which is, uh, interesting, and also more of something to fix in Smithay? cc @cmeissl

**Comment by cmeissl** [comment]
From the stack it seems that getting the resources of the drm device failed. The only input provided to this drm IOCTL is the `fd` of the device. So something seems to be wrong with the device itself.

**Comment by robbins** [comment]
FWIW I didn't have this issue on other Wayland compositors like Hyprland, and it was happening consistently on Niri (last ~5 suspend/resumes), but I just had one resume that didn't result in a Niri crash.

Here's the journalctl in case it can rule out some logging that isn't actually related to the cause of the issue in the previous log: https://pastebin.com/erPW8Bb5

**Comment by cmeissl** [comment]
Looking at both logs, the first one contains some kernel warnings related to suspending the amd gpu, while the second one does not. I wonder if this is more related to how suspending is done and the crash on resume is just a side effect of the error on suspend. Anyway, the unwrap in `smithay` is not necessary and we can change that to bubble up the error. 

I drafted that in both smithay and niri: https://github.com/YaLTeR/niri/pull/513
This should get rid of the crash by ignoring the error. So it would be interesting to know if the device changed
is followed by another one that succeeds or if it is just dead afterwards.

**Comment by SalmanFarooqShiekh** [comment]
Also happens for me, when resuming by opening the laptop lid.

**Comment by YaLTeR** [comment]
I think this should be fixed now because that unwrap was converted into a warning.
