### ISSUE TITLE
Niri crashed on monitor reconnect.

### ISSUE THREAD

**Issue by TheAngusMcFire** [YaLTeR/niri#556]
Niri crashed while I was disconnecting and reconnecting 2 monitors, I used a KVM switch.

```
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.275134Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.291783Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.308606Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.325138Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.341791Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.358453Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.375199Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.391826Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.408533Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.425153Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.441821Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 21:31:01 arch-tower-pc niri[1652]: 2024-07-23T19:31:01.458866Z  WARN niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
Jul 23 23:15:10 arch-tower-pc niri[1652]: failed to read client connection (pid 960366)
Jul 23 23:15:15 arch-tower-pc niri[1652]: error in client communication (pid 997018)
Jul 23 23:40:03 arch-tower-pc niri[1652]: 2024-07-23T21:40:03.249707Z DEBUG niri::backend::tty: device changed: 57857
Jul 23 23:40:03 arch-tower-pc niri[1652]: 2024-07-23T21:40:03.281533Z DEBUG niri::backend::tty: disconnecting connector: "DP-1"
Jul 23 23:40:06 arch-tower-pc niri[1652]: 2024-07-23T21:40:06.786582Z DEBUG niri::backend::tty: device changed: 57857
Jul 23 23:40:06 arch-tower-pc niri[1652]: 2024-07-23T21:40:06.818213Z DEBUG niri::backend::tty: connecting connector: DP-1
Jul 23 23:40:06 arch-tower-pc niri[1652]: 2024-07-23T21:40:06.818257Z  WARN niri::backend::tty: configured mode 7680x2160 could not be found, falling back to preferred
Jul 23 23:40:06 arch-tower-pc niri[1652]: 2024-07-23T21:40:06.818262Z DEBUG niri::backend::tty: picking mode: Mode { name: "5120x1440", clock: 469000, size: (5120, 1440), hsync: (5168, 5200, 5280), vsync: (1443, 1453, 1481), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
Jul 23 23:40:06 arch-tower-pc niri[1652]: 2024-07-23T21:40:06.818299Z DEBUG niri::backend::tty: set max bpc to 8
Jul 23 23:40:06 arch-tower-pc niri[1652]: 2024-07-23T21:40:06.821158Z DEBUG niri::niri: putting output DP-1 at x=0 y=1440
Jul 23 23:41:33 arch-tower-pc niri[1652]: error in client communication (pid 1262842)
Jul 23 23:41:35 arch-tower-pc niri[1652]: 2024-07-23T21:41:35.650801Z DEBUG niri_config: loaded config from "/home/angus/.config/niri/config.kdl"
Jul 23 23:41:44 arch-tower-pc niri[1652]: 2024-07-23T21:41:44.881754Z DEBUG niri::backend::tty: device changed: 57857
Jul 23 23:41:44 arch-tower-pc niri[1652]: 2024-07-23T21:41:44.892459Z DEBUG niri::backend::tty: disconnecting connector: "DP-1"
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.056957Z DEBUG niri::backend::tty: disconnecting connector: "DP-2"
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.122153Z DEBUG niri::backend::tty: device changed: 57857
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.146435Z DEBUG niri::backend::tty: connecting connector: DP-1
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.146470Z DEBUG niri::backend::tty: picking mode: Mode { name: "7680x2160", clock: 2224750, size: (7680, 2160), hsync: (7928, 7960, 8240), vsync: (2163, 2173, 2250), hskew: 0, vscan: 0, vrefresh: 120, mode_type: ModeTypeFlags(DRIVER) }
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.146502Z DEBUG niri::backend::tty: set max bpc to 8
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.149144Z DEBUG niri::niri: putting output DP-1 at x=0 y=1440
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.149164Z DEBUG niri::backend::tty: connecting connector: DP-2
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.149187Z DEBUG niri::backend::tty: picking mode: Mode { name: "2560x1440", clock: 241500, size: (2560, 1440), hsync: (2608, 2640, 2720), vsync: (1443, 1448, 1481), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.149220Z DEBUG niri::backend::tty: set max bpc to 8
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.151247Z DEBUG niri::niri: putting output DP-2 at x=0 y=0
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.151478Z DEBUG niri::backend::tty: device changed: 57857
Jul 23 23:42:05 arch-tower-pc niri[1652]: 2024-07-23T21:42:05.179805Z DEBUG niri::backend::tty: device changed: 57857
Jul 23 23:42:05 arch-tower-pc niri[1652]: thread 'main' panicked at src/backend/tty.rs:1165:34:
Jul 23 23:42:05 arch-tower-pc niri[1652]: internal error: entered unreachable code
Jul 23 23:42:05 arch-tower-pc niri[1652]: stack backtrace:
Jul 23 23:42:06 arch-tower-pc niri[1652]:    0: rust_begin_unwind
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
Jul 23 23:42:06 arch-tower-pc niri[1652]:    1: core::panicking::panic_fmt
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
Jul 23 23:42:06 arch-tower-pc niri[1652]:    2: core::panicking::panic
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:146:5
Jul 23 23:42:06 arch-tower-pc niri[1652]:    3: on_vblank
Jul 23 23:42:06 arch-tower-pc niri[1652]:    4: {closure#0}
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at ./repos/niri/src/backend/tty.rs:560:25
Jul 23 23:42:06 arch-tower-pc niri[1652]:    5: {closure#0}<niri::niri::State, smithay::backend::drm::device::DrmDeviceNotifier, niri::backend::tty::{impl#1}::device_added::{closure_env#0}>
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.0/src/sources/mod.rs:327:61
Jul 23 23:42:06 arch-tower-pc niri[1652]:    6: process_events<calloop::sources::{impl#4}::process_events::{closure_env#0}<niri::niri::State, smithay::backend::drm::device::DrmDeviceNotifier, niri::backend::tty::{impl#1}::device_added::{closure_env#0}>>
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at ./.cargo/git/checkouts/smithay-b5a338d5236320f6/234586d/src/backend/drm/device/mod.rs:538:25
Jul 23 23:42:06 arch-tower-pc niri[1652]:    7: process_events<niri::niri::State, smithay::backend::drm::device::DrmDeviceNotifier, niri::backend::tty::{impl#1}::device_added::{closure_env#0}>
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.0/src/sources/mod.rs:326:9
Jul 23 23:42:06 arch-tower-pc niri[1652]:    8: dispatch_events<niri::niri::State>
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.0/src/loop_logic.rs:445:31
Jul 23 23:42:06 arch-tower-pc niri[1652]:    9: dispatch<niri::niri::State, core::option::Option<core::time::Duration>>
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.0/src/loop_logic.rs:559:9
Jul 23 23:42:06 arch-tower-pc niri[1652]:   10: run<niri::niri::State, niri::main::{closure_env#4}, core::option::Option<core::time::Duration>>
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.0/src/loop_logic.rs:596:13
Jul 23 23:42:06 arch-tower-pc niri[1652]:   11: main
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at ./repos/niri/src/main.rs:264:5
Jul 23 23:42:06 arch-tower-pc niri[1652]:   12: call_once<fn() -> core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>, ()>
Jul 23 23:42:06 arch-tower-pc niri[1652]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
Jul 23 23:42:06 arch-tower-pc niri[1652]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
### System Information

* niri version:  niri 0.1.7 (a38a7b4-modified)

* Distro: Arch Linux

* GPU: AMD RX 6600 XT

* CPU: AMD Ryzen 7 2700

**Comment by YaLTeR** [comment]
Thanks. I'll need to take a more in-depth look at this.

**Comment by YaLTeR** [comment]
I'm not sure how exactly this can happen but I pushed a check so it shouldn't crash in this case. af904d23acc7980fbf3aedf173dc96af1dd580b9
