### ISSUE TITLE
0.1.8: Issue when running tests

### ISSUE THREAD

**Issue by dvzrv** [YaLTeR/niri#588]
When trying to build the package for Arch Linux I unfortunately ran into many failing tests:

```shell
running 44 tests
test backend::tty::tests::truncate_to_nul_works ... ok
test input::tests::comp_mod_handling ... ok
test layout::tests::config_change_updates_cached_sizes ... FAILED
test input::tests::bindings_suppress_keys ... FAILED
test layout::tests::large_fractional_strut ... ok
test layout::tests::operations_from_starting_state_dont_panic ... ok
test layout::tests::removing_all_outputs_preserves_empty_named_workspaces ... ok
test layout::tests::random_operations_dont_panic ... ok
test layout::tests::working_area_starts_at_physical_pixel ... ok
test utils::scale::tests::guess_monitor_scale_unknown_size ... ok
test utils::scale::tests::test_round_scale ... ok
test utils::scale::tests::test_guess_monitor_scale ... ok
test layout::tests::workspace_cleanup_during_switch ... FAILED
test layout::tests::fullscreen ... ok
test layout::tests::large_negative_height_change ... ok
test layout::tests::large_max_size ... ok
test layout::tests::move_workspace_to_output ... ok
test layout::tests::empty_workspaces_dont_move_back_to_original_output ... FAILED
test layout::tests::move_to_workspace_by_idx_does_not_leave_empty_workspaces ... FAILED
test layout::tests::open_right_of_on_different_workspace ... FAILED
test layout::tests::primary_active_workspace_idx_not_updated_on_output_add ... FAILED
test layout::tests::focus_workspace_by_idx_does_not_leave_empty_workspaces ... FAILED
test layout::tests::removing_output_must_keep_empty_focus_on_primary ... ok
test layout::tests::unfullscreen_view_offset_not_reset_on_quick_double_toggle ... ok
test layout::tests::workspace_transfer_during_switch_gets_cleaned_up ... FAILED
test layout::tests::window_closed_on_previous_workspace ... FAILED
test layout::tests::unfullscreen_view_offset_not_reset_on_consume ... FAILED
test layout::tests::workspace_transfer_during_switch ... FAILED
test layout::tests::workspace_transfer_during_switch_from_last ... FAILED
test layout::tests::unfullscreen_window_in_column ... FAILED
test layout::tests::unfullscreen_view_offset_set_on_fullscreening_inactive_tile_in_column ... FAILED
test layout::tests::unfullscreen_view_offset_not_reset_on_removal ... FAILED
test layout::tests::unfullscreen_view_offset_not_reset_on_gesture ... FAILED
test utils::watcher::tests::change_file ... ok
test utils::watcher::tests::change_file_in_linked_dir ... ok
test utils::watcher::tests::change_linked_file ... ok
test utils::watcher::tests::create_dir_and_file ... ok
test utils::watcher::tests::recreate_dir ... ok
test utils::watcher::tests::create_file ... ok
test utils::watcher::tests::recreate_file ... ok
test utils::watcher::tests::swap_dir ... ok
test utils::watcher::tests::swap_just_link ... ok
test utils::watcher::tests::swap_dir_link ... ok
test layout::tests::operations_dont_panic ... FAILED

failures:

---- layout::tests::config_change_updates_cached_sizes stdout ----
thread 'layout::tests::config_change_updates_cached_sizes' panicked at niri-config/src/lib.rs:1375:21:
span! without a running Client

---- input::tests::bindings_suppress_keys stdout ----
thread 'input::tests::bindings_suppress_keys' panicked at niri-config/src/lib.rs:1375:21:
span! without a running Client
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- layout::tests::workspace_cleanup_during_switch stdout ----
thread 'layout::tests::workspace_cleanup_during_switch' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::empty_workspaces_dont_move_back_to_original_output stdout ----
thread 'layout::tests::empty_workspaces_dont_move_back_to_original_output' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::move_to_workspace_by_idx_does_not_leave_empty_workspaces stdout ----
thread 'layout::tests::move_to_workspace_by_idx_does_not_leave_empty_workspaces' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::open_right_of_on_different_workspace stdout ----
thread 'layout::tests::open_right_of_on_different_workspace' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::primary_active_workspace_idx_not_updated_on_output_add stdout ----
thread 'layout::tests::primary_active_workspace_idx_not_updated_on_output_add' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::focus_workspace_by_idx_does_not_leave_empty_workspaces stdout ----
thread 'layout::tests::focus_workspace_by_idx_does_not_leave_empty_workspaces' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::workspace_transfer_during_switch_gets_cleaned_up stdout ----
thread 'layout::tests::workspace_transfer_during_switch_gets_cleaned_up' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::window_closed_on_previous_workspace stdout ----
thread 'layout::tests::window_closed_on_previous_workspace' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::unfullscreen_view_offset_not_reset_on_consume stdout ----
thread 'layout::tests::unfullscreen_view_offset_not_reset_on_consume' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::workspace_transfer_during_switch stdout ----
thread 'layout::tests::workspace_transfer_during_switch' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::workspace_transfer_during_switch_from_last stdout ----
thread 'layout::tests::workspace_transfer_during_switch_from_last' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::unfullscreen_window_in_column stdout ----
thread 'layout::tests::unfullscreen_window_in_column' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::unfullscreen_view_offset_set_on_fullscreening_inactive_tile_in_column stdout ----
thread 'layout::tests::unfullscreen_view_offset_set_on_fullscreening_inactive_tile_in_column' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::unfullscreen_view_offset_not_reset_on_removal stdout ----
thread 'layout::tests::unfullscreen_view_offset_not_reset_on_removal' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::unfullscreen_view_offset_not_reset_on_gesture stdout ----
thread 'layout::tests::unfullscreen_view_offset_not_reset_on_gesture' panicked at src/animation/mod.rs:162:21:
span! without a running Client

---- layout::tests::operations_dont_panic stdout ----
thread 'layout::tests::operations_dont_panic' panicked at src/animation/mod.rs:162:21:
span! without a running Client
failures:
    input::tests::bindings_suppress_keys
    layout::tests::config_change_updates_cached_sizes
    layout::tests::empty_workspaces_dont_move_back_to_original_output
    layout::tests::focus_workspace_by_idx_does_not_leave_empty_workspaces
    layout::tests::move_to_workspace_by_idx_does_not_leave_empty_workspaces
    layout::tests::open_right_of_on_different_workspace
    layout::tests::operations_dont_panic
    layout::tests::primary_active_workspace_idx_not_updated_on_output_add
    layout::tests::unfullscreen_view_offset_not_reset_on_consume
    layout::tests::unfullscreen_view_offset_not_reset_on_gesture
    layout::tests::unfullscreen_view_offset_not_reset_on_removal
    layout::tests::unfullscreen_view_offset_set_on_fullscreening_inactive_tile_in_column
    layout::tests::unfullscreen_window_in_column
    layout::tests::window_closed_on_previous_workspace
    layout::tests::workspace_cleanup_during_switch
    layout::tests::workspace_transfer_during_switch
    layout::tests::workspace_transfer_during_switch_from_last
    layout::tests::workspace_transfer_during_switch_gets_cleaned_up

test result: FAILED. 26 passed; 18 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.77s

error: test failed, to rerun pass `--lib`
```

Do I need to run tests differently now?
I tried also adding `--exclude niri-visual-tests` but that didn't change the outcome.

### System Information

* niri version: 0.1.8

* Distro: Arch Linux

* GPU: AMD/ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT

* CPU: AMD Ryzen 9 3900X

**Comment by YaLTeR** [comment]
You seem to be using `--all-features`. Do not use `--all-features`, they contain debugging-only build flags.

**Comment by dvzrv** [comment]
Ah right, thanks! That was it :partying_face:

**Comment by YaLTeR** [comment]
Thanks for the quick update!
