### ISSUE TITLE
niri crashes (randomly) when resuming from S3/ hybrid sleep

### ISSUE THREAD

**Issue by dantefromhell** [YaLTeR/niri#615]
This crash happened the first time ever to me today. I regularly suspend my laptop using `systemctl hybrid-sleep`, sometimes the system resumes from S3 sometimes from disc.

The following stack-trace happened today when resuming from S3, killing my niri process
```
Aug 21 15:05:53 aitutaki niri[2835]: 2024-08-21T15:05:53.550268Z DEBUG niri::backend::tty: device changed: 57857
Aug 21 15:05:53 aitutaki niri[2835]: 2024-08-21T15:05:53.596544Z DEBUG niri::backend::tty: disconnecting connector: "DP-4"
Aug 21 15:05:54 aitutaki niri[2835]: 2024-08-21T15:05:54.849684Z DEBUG niri::backend::tty: device changed: 57857
Aug 21 15:05:54 aitutaki niri[2835]: 2024-08-21T15:05:54.936411Z DEBUG niri::backend::tty: connecting connector: DP-4
Aug 21 15:05:54 aitutaki niri[2835]: 2024-08-21T15:05:54.936481Z DEBUG niri::backend::tty: picking mode: Mode { name: "3840x2160", clock: 594000, size: (3840, 2160), hsync: (4016, 4104, 4400), vsync: (2168, 2178, 2250), hskew: 0, vscan: 0, vrefresh>
Aug 21 15:05:54 aitutaki niri[2835]: 2024-08-21T15:05:54.936533Z DEBUG niri::backend::tty: set max bpc to 8
Aug 21 15:05:54 aitutaki niri[2835]: 2024-08-21T15:05:54.936578Z  WARN niri::backend::tty: cannot enable VRR because connector is not vrr_capable
Aug 21 15:05:54 aitutaki niri[2835]: 2024-08-21T15:05:54.936689Z  WARN niri::backend::tty: error disabling VRR
Aug 21 15:05:54 aitutaki niri[2835]: 2024-08-21T15:05:54.947521Z DEBUG niri::niri: putting output DP-4 at x=0 y=0
Aug 21 15:05:54 aitutaki niri[2835]: thread 'main' panicked at src/backend/tty.rs:1239:36:
Aug 21 15:05:54 aitutaki niri[2835]: internal error: entered unreachable code
Aug 21 15:05:54 aitutaki niri[2835]: stack backtrace:
Aug 21 15:05:55 aitutaki niri[2835]:    0: rust_begin_unwind
Aug 21 15:05:55 aitutaki niri[2835]:    1: core::panicking::panic_fmt
Aug 21 15:05:55 aitutaki niri[2835]:    2: core::panicking::panic
Aug 21 15:05:55 aitutaki niri[2835]:    3: on_vblank
Aug 21 15:05:55 aitutaki niri[2835]:    4: {closure#0}
Aug 21 15:05:55 aitutaki niri[2835]:              at /build/source/src/backend/tty.rs:594:25
Aug 21 15:05:55 aitutaki niri[2835]:    5: {closure#0}<niri::niri::State, smithay::backend::drm::device::DrmDeviceNotifier, niri::backend::tty::{impl#1}::device_added::{closure_env#0}>
Aug 21 15:05:55 aitutaki niri[2835]:              at /build/cargo-vendor-dir/calloop-0.14.0/src/sources/mod.rs:327:61
Aug 21 15:05:55 aitutaki niri[2835]:    6: process_events<calloop::sources::{impl#4}::process_events::{closure_env#0}<niri::niri::State, smithay::backend::drm::device::DrmDeviceNotifier, niri::backend::tty::{impl#1}::device_added::{closure_env#0}>>
Aug 21 15:05:55 aitutaki niri[2835]:              at /build/cargo-vendor-dir/smithay-0.3.0/src/backend/drm/device/mod.rs:557:25
Aug 21 15:05:55 aitutaki niri[2835]:    7: process_events<niri::niri::State, smithay::backend::drm::device::DrmDeviceNotifier, niri::backend::tty::{impl#1}::device_added::{closure_env#0}>
Aug 21 15:05:55 aitutaki niri[2835]:              at /build/cargo-vendor-dir/calloop-0.14.0/src/sources/mod.rs:326:9
Aug 21 15:05:55 aitutaki niri[2835]:    8: dispatch_events<niri::niri::State>
Aug 21 15:05:55 aitutaki niri[2835]:              at /build/cargo-vendor-dir/calloop-0.14.0/src/loop_logic.rs:445:31
Aug 21 15:05:55 aitutaki niri[2835]:    9: dispatch<niri::niri::State, core::option::Option<core::time::Duration>>
Aug 21 15:05:55 aitutaki niri[2835]:              at /build/cargo-vendor-dir/calloop-0.14.0/src/loop_logic.rs:559:9
Aug 21 15:05:55 aitutaki niri[2835]:   10: run<niri::niri::State, niri::main::{closure_env#4}, core::option::Option<core::time::Duration>>
Aug 21 15:05:55 aitutaki niri[2835]:              at /build/cargo-vendor-dir/calloop-0.14.0/src/loop_logic.rs:596:13
Aug 21 15:05:55 aitutaki niri[2835]:   11: main
Aug 21 15:05:55 aitutaki niri[2835]:              at /build/source/src/main.rs:264:5
Aug 21 15:05:55 aitutaki niri[2835]:   12: call_once<fn() -> core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>, ()>
Aug 21 15:05:55 aitutaki niri[2835]:              at /build/rustc-1.80.1-src/library/core/src/ops/function.rs:250:5
Aug 21 15:05:55 aitutaki niri[2835]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aug 21 15:05:55 aitutaki niri[2835]: 2024-08-21T15:05:55.473736Z DEBUG niri::utils::watcher: exiting watcher thread for /home/dante/.config/niri/config.kdl
Aug 21 15:05:56 aitutaki systemd[2786]: niri.service: Main process exited, code=exited, status=101/n/a
Aug 21 15:05:56 aitutaki systemd[2786]: niri.service: Failed with result 'exit-code'.
Aug 21 15:05:56 aitutaki systemd[2786]: niri.service: Consumed 5min 50.443s CPU time, 680.3M memory peak.
```
Uncertain if this is related to #509 given the different stack-trace.

The issue title says "randomly" as this crash doesn't seem to happen everytime I resume this way. But I'll do more testing and will update the issue.

### System Information

* niri version: niri stable 0.1.8

* Distro: NixOS unstable, using https://github.com/sodiboo/niri-flake?rev=4cac74d2ddab7d2b7769e9dd30616de9decfc474

* GPU: 
```
00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01) (prog-if 00 [VGA controller])
        Subsystem: Framework Computer Inc. Device 0001
        Flags: bus master, fast devsel, latency 0, IRQ 132, IOMMU group 4
        Memory at 605c000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 4000000000 (64-bit, prefetchable) [size=256M]
        I/O ports at 3000 [size=64]
        Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Root Complex Integrated Endpoint, IntMsgNum 0
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit-
        Capabilities: [d0] Power Management version 2
        Capabilities: [100] Process Address Space ID (PASID)
        Capabilities: [200] Address Translation Service (ATS)
        Capabilities: [300] Page Request Interface (PRI)
        Capabilities: [320] Single Root I/O Virtualization (SR-IOV)
        Kernel driver in use: i915
        Kernel modules: i915
```

* CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

**Comment by YaLTeR** [comment]
Huh, I guess this S3 sleep can result in weird output states.. I'll add more graceful fallbacks for this.

**Comment by andybalholm** [comment]
I don't know if it's the same issue, but I'm seeing occasional crashes when unlocking my computer after powering off the screens (not truly sleeping). My laptop's internal monitor comes back on, but before my external monitor finishes coming back on, Niri exits.

**Comment by YaLTeR** [comment]
Please post the panic backtrace from niri output.

**Comment by andybalholm** [comment]
How can I access that output? I'm starting Niri from my display manager, and it goes back to the display manager after Niri quits.

**Comment by YaLTeR** [comment]
journalctl --user-unit=niri -eb

**Comment by andybalholm** [comment]
It doesn't give me a full backtrace, but it might be enough to be helpful:

```
Aug 30 08:20:48 andys-laptop niri[1716484]: 2024-08-30T15:20:48.751952Z  INFO niri::niri: unlocking session
Aug 30 08:20:48 andys-laptop niri[1716484]: 2024-08-30T15:20:48.824260Z DEBUG niri::backend::tty: device changed: 57857
Aug 30 08:20:49 andys-laptop niri[1716484]: 2024-08-30T15:20:49.466384Z DEBUG niri::backend::tty: disconnecting connector: "HDMI-A-1"
Aug 30 08:20:49 andys-laptop niri[1716484]: 2024-08-30T15:20:49.467161Z DEBUG niri::niri: putting output eDP-1 at x=3480 y=0
Aug 30 08:20:49 andys-laptop niri[1716484]: 2024-08-30T15:20:49.585571Z DEBUG niri::backend::tty: device changed: 57857
Aug 30 08:20:50 andys-laptop niri[1716484]: 2024-08-30T15:20:50.464006Z DEBUG niri::backend::tty: connecting connector: HDMI-A-1
Aug 30 08:20:50 andys-laptop niri[1716484]: 2024-08-30T15:20:50.464048Z  WARN niri::backend::tty: configured mode 3480x2160 could not be found, falling back to preferred
Aug 30 08:20:50 andys-laptop niri[1716484]: 2024-08-30T15:20:50.464053Z DEBUG niri::backend::tty: picking mode: Mode { name: "3840x2160", clock: 297000, size: (3840, 2160), hsync: (4016, 4104, 4400>
Aug 30 08:20:50 andys-laptop niri[1716484]: 2024-08-30T15:20:50.464151Z DEBUG niri::backend::tty: set max bpc to 8
Aug 30 08:20:50 andys-laptop niri[1716484]: 2024-08-30T15:20:50.482721Z DEBUG niri::niri: putting output HDMI-A-1 at x=0 y=0
Aug 30 08:20:50 andys-laptop niri[1716484]: 2024-08-30T15:20:50.482741Z  WARN niri::niri: output eDP-1 at x=3480 y=0 sized 1920x1080 overlaps an existing output at x=0 y=0 sized 3840x2160, falling >
Aug 30 08:20:50 andys-laptop niri[1716484]: 2024-08-30T15:20:50.482748Z DEBUG niri::niri: putting output eDP-1 at x=3840 y=0
Aug 30 08:20:50 andys-laptop niri[1716484]: thread 'main' panicked at src/backend/tty.rs:1239:36:
Aug 30 08:20:50 andys-laptop niri[1716484]: internal error: entered unreachable code
Aug 30 08:20:50 andys-laptop niri[1716484]: stack backtrace:
Aug 30 08:20:50 andys-laptop niri[1716484]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aug 30 08:20:50 andys-laptop niri[1716484]: 2024-08-30T15:20:50.855854Z DEBUG niri::utils::watcher: exiting watcher thread for /home/andy/.config/niri/config.kdl
Aug 30 08:20:52 andys-laptop systemd[968]: niri.service: Main process exited, code=exited, status=101/n/a
Aug 30 08:20:52 andys-laptop systemd[968]: niri.service: Failed with result 'exit-code'.
Aug 30 08:20:52 andys-laptop systemd[968]: niri.service: Consumed 1h 32min 18.591s CPU time, 711.2M memory peak, 262.8M memory swap peak.
```

**Comment by YaLTeR** [comment]
Looks like the same crash. Huh

**Comment by andybalholm** [comment]
That helps to prove it's the same issue as mine, since I was restarting the monitors after doing `power-off-monitors`.

**Comment by YaLTeR** [comment]
I added some more fallbacks in 6b6a84e55be388589e49fc9ddd8502dd2da7aca9 so this should hopefully no longer crash.

**Comment by 2gn** [comment]
I'm not sure if it's relevant, but niri crashed on my system as well after hibernation.

```
Oct 19 19:37:45 aiw niri[2084]: libinput error: event5  - SYNA8020:00 06CB:CE5C Touchpad: kernel bug: Touch jump detected and discarded.
Oct 19 19:37:45 aiw niri[2084]: See https://wayland.freedesktop.org/libinput/doc/1.22.1/touchpad-jumping-cursors.html for details
Oct 19 19:37:46 aiw niri[2084]: libinput error: event5  - SYNA8020:00 06CB:CE5C Touchpad: kernel bug: Touch jump detected and discarded.
Oct 19 19:37:46 aiw niri[2084]: See https://wayland.freedesktop.org/libinput/doc/1.22.1/touchpad-jumping-cursors.html for details
Oct 19 19:37:46 aiw niri[2084]: libinput error: event5  - SYNA8020:00 06CB:CE5C Touchpad: WARNING: log rate limit exceeded (5 msgs per 24h). Discarding future messages.
Oct 19 20:41:24 aiw niri[2084]: libinput error: event2  - Lid Switch: client bug: event processing lagging behind by 1623ms, your system is too slow
Oct 19 20:42:27 aiw niri[2084]: 2024-10-19T11:42:27.567123Z DEBUG niri::backend::tty: pausing session
Oct 19 20:42:37 aiw systemd[1913]: Stopping app-niri-fuzzel-2847.scope...
Oct 19 20:42:37 aiw systemd[1913]: Stopping app-niri-swaybg-2315.scope...
Oct 19 20:42:37 aiw systemd[1913]: Stopping app-niri-wezterm-2307.scope...
Oct 19 20:42:37 aiw niri[2084]: 2024-10-19T11:42:37.418096Z  WARN niri::backend::tty: device is inactive
Oct 19 20:42:37 aiw systemd[1913]: Stopped app-niri-swaybg-2315.scope.
Oct 19 20:42:37 aiw niri[2084]: 2024-10-19T11:42:37.446789Z  WARN niri::backend::tty: device is inactive
Oct 19 20:42:37 aiw systemd[1913]: Stopped app-niri-wezterm-2307.scope.
Oct 19 20:42:37 aiw systemd[1913]: app-niri-wezterm-2307.scope: Consumed 6.721s CPU time.
Oct 19 20:42:37 aiw systemd[1913]: Stopping niri.service - A scrollable-tiling Wayland compositor...
Oct 19 20:42:37 aiw systemd[1913]: Stopped app-niri-fuzzel-2847.scope.
Oct 19 20:42:37 aiw systemd[1913]: app-niri-fuzzel-2847.scope: Consumed 1min 9.365s CPU time.
Oct 19 20:42:37 aiw systemd[1913]: Stopped niri.service - A scrollable-tiling Wayland compositor.
Oct 19 20:42:37 aiw systemd[1913]: niri.service: Consumed 22.930s CPU time.
```

**Comment by YaLTeR** [comment]
I don't see a crash in that log?
