### ISSUE TITLE
Niri panic on monitor change

### ISSUE THREAD

**Issue by brandoncazander** [YaLTeR/niri#739]
Loving niri so far! I've encountered an occasional crash when switching monitor inputs. I have a single output enabled in my niri config (DP-5, USB-C monitor). I use the same monitor (on a different input) for another machine, so I switch back and forth occasionally.

I've set `RUST_BACKTRACE=full` in the service environment variables, so if it happens again and that's helpful I can update this issue. Also happy to build and run from source to debug or test fixes if needed.

```
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.219526Z DEBUG niri::backend::tty: connecting connector: DP-5
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.219724Z DEBUG niri::backend::tty: picking mode: Mode { name: "3440x1440", clock: 319750, size: (3440, 1440), hsync: (3488, 3520, 3600), vsync: (1443, 1453, 1481), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeF>
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.219901Z DEBUG niri::backend::tty: set max bpc to 8
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.235360Z DEBUG niri::niri: putting output DP-5 at x=0 y=0
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.235640Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.334751Z  WARN niri::backend::tty: error getting properties: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.334892Z  WARN niri::backend::tty: error getting EDID info for DP-5: no EDID property
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.334989Z  WARN niri::backend::tty: error getting properties: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.335099Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.410460Z  WARN niri::backend::tty: error getting EDID info for DP-5: error getting EDID blob value
Oct 15 06:06:29 lois niri[2504143]: Caused by:
Oct 15 06:06:29 lois niri[2504143]:     No such file or directory (os error 2)
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.410909Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.457136Z DEBUG niri::backend::tty: disconnecting connector: "DP-5"
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.457509Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:29 lois niri[2504143]: 2024-10-15T13:06:29.648073Z DEBUG niri::backend::tty: connecting connector: DP-5

(snip)

Oct 15 06:06:33 lois niri[2504143]: 2024-10-15T13:06:33.040174Z DEBUG niri::backend::tty: connecting connector: DP-5
Oct 15 06:06:33 lois niri[2504143]: 2024-10-15T13:06:33.040390Z DEBUG niri::backend::tty: picking mode: Mode { name: "3440x1440", clock: 319750, size: (3440, 1440), hsync: (3488, 3520, 3600), vsync: (1443, 1453, 1481), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeF>
Oct 15 06:06:33 lois niri[2504143]: 2024-10-15T13:06:33.040546Z DEBUG niri::backend::tty: set max bpc to 8
Oct 15 06:06:33 lois niri[2504143]: 2024-10-15T13:06:33.054623Z DEBUG niri::niri: putting output DP-5 at x=0 y=0
Oct 15 06:06:33 lois niri[2504143]: 2024-10-15T13:06:33.054830Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:33 lois niri[2504143]: 2024-10-15T13:06:33.243841Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:33 lois niri[2504143]: 2024-10-15T13:06:33.437116Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:33 lois niri[2504143]: 2024-10-15T13:06:33.602676Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:33 lois niri[2504143]: 2024-10-15T13:06:33.769690Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:34 lois niri[2504143]: 2024-10-15T13:06:33.927923Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:34 lois niri[2504143]: 2024-10-15T13:06:34.088410Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:34 lois niri[2504143]: 2024-10-15T13:06:34.253876Z DEBUG niri::backend::tty: device changed: 57857
Oct 15 06:06:34 lois niri[2504143]: thread 'main' panicked at src/niri.rs:2548:55:
Oct 15 06:06:34 lois niri[2504143]: called `Option::unwrap()` on a `None` value
Oct 15 06:06:34 lois niri[2504143]: stack backtrace:
Oct 15 06:06:34 lois niri[2504143]:    0: rust_begin_unwind
Oct 15 06:06:34 lois niri[2504143]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
Oct 15 06:06:34 lois niri[2504143]:    1: core::panicking::panic_fmt
Oct 15 06:06:34 lois niri[2504143]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
Oct 15 06:06:34 lois niri[2504143]:    2: core::panicking::panic
Oct 15 06:06:34 lois niri[2504143]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:148:5
Oct 15 06:06:34 lois niri[2504143]:    3: core::option::unwrap_failed
Oct 15 06:06:34 lois niri[2504143]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:2020:5
Oct 15 06:06:34 lois niri[2504143]:    4: unwrap<&mut niri::niri::OutputState>
Oct 15 06:06:34 lois niri[2504143]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:970:21
Oct 15 06:06:34 lois niri[2504143]:    5: queue_redraw
Oct 15 06:06:34 lois niri[2504143]:              at ./Documents/repos/niri/src/niri.rs:2548:55
Oct 15 06:06:34 lois niri[2504143]:    6: {closure#7}
Oct 15 06:06:34 lois niri[2504143]:              at ./Documents/repos/niri/src/backend/tty.rs:1058:17
Oct 15 06:06:34 lois niri[2504143]:    7: {closure#0}<niri::niri::State, niri::backend::tty::{impl#1}::connector_connected::{closure_env#7}>
Oct 15 06:06:34 lois niri[2504143]:              at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.1/src/loop_logic.rs:156:17
Oct 15 06:06:34 lois niri[2504143]:    8: dispatch<niri::niri::State, calloop::loop_logic::{impl#3}::insert_idle::{closure_env#0}<niri::niri::State, niri::backend::tty::{impl#1}::connector_connected::{closure_env#7}>>
Oct 15 06:06:34 lois niri[2504143]:              at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.1/src/sources/mod.rs:597:13
Oct 15 06:06:34 lois niri[2504143]:    9: dispatch_idles<niri::niri::State>
Oct 15 06:06:34 lois niri[2504143]:              at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.1/src/loop_logic.rs:533:13
Oct 15 06:06:34 lois niri[2504143]:   10: dispatch<niri::niri::State, core::option::Option<core::time::Duration>>
Oct 15 06:06:34 lois niri[2504143]:              at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.1/src/loop_logic.rs:551:9
Oct 15 06:06:34 lois niri[2504143]:   11: run<niri::niri::State, niri::main::{closure_env#4}, core::option::Option<core::time::Duration>>
Oct 15 06:06:34 lois niri[2504143]:              at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.1/src/loop_logic.rs:587:13
Oct 15 06:06:34 lois niri[2504143]:   12: main
Oct 15 06:06:34 lois niri[2504143]:              at ./Documents/repos/niri/src/main.rs:256:5
Oct 15 06:06:34 lois niri[2504143]:   13: call_once<fn() -> core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>, ()>
Oct 15 06:06:34 lois niri[2504143]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
Oct 15 06:06:34 lois niri[2504143]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### System Information

* niri version: niri 0.1.9 (v0.1.9)

* Distro: Ubuntu 24.04.1

* GPU: Intel UHD 770

* CPU: Core i7-12850HX

**Comment by YaLTeR** [comment]
Thanks, I see the race condition ish thing that can cause this.

**Comment by YaLTeR** [comment]
Added a check, should be fixed now.
