### ISSUE TITLE
 Niri fails to start on Ubuntu 24.10 with X Elite

### ISSUE THREAD

**Issue by contra-bit** [YaLTeR/niri#799]
**Description:**

I am experiencing an issue with Niri, where it fails to start when using the DRM device on Ubuntu 24.10. I have built Niri from the main branch and am using the latest version.

**Steps to Reproduce:**

1. Build Niri from the main branch.
2. Select the render-drm-device option.
3. Attempt to start Niri from TTY (niri-session) or GDM.

**Expected Behavior:**

Niri should start successfully and display the desktop environment.

**Actual Behavior:**

Niri fails to start and crashes with a segmentation fault (SIGSEGV).

**Debugging Information:**

When running the `cargo test` and debugging with GDB, I get the following output:

```
Thread 2 "cargo" received signal SIGUSR1, User defined signal 1.
[Switching to Thread 0xfffff720eee0 (LWP 24004)]
syscall () at ../sysdeps/unix/sysv/linux/aarch64/syscall.S:39
warning: 39	../sysdeps/unix/sysv/linux/aarch64/syscall.S: No such file or directory
```

When running Niri from TTY, I get the following output:

```
2024-11-12T10:25:22.025775Z  WARN niri: running as a session but DISPLAY is set, removing it
2024-11-12T10:25:22.025807Z  WARN niri: running as a session but WAYLAND_DISPLAY is set, removing it
2024-11-12T10:25:22.025819Z  INFO niri: starting version 0.1.10 (c2c415d-modified)
2024-11-12T10:25:22.042730Z DEBUG niri_config: loaded config from "/home/liam/.config/niri/config.kdl"
2024-11-12T10:25:22.062356Z DEBUG niri::backend::tty: attempting to use render node from config: "/dev/dri/renderD128"
2024-11-12T10:25:22.062468Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
2024-11-12T10:25:22.094730Z DEBUG niri::backend::tty: device added: 57857 "/dev/dri/card1"
2024-11-12T10:25:22.094851Z  WARN niri::backend::tty: error adding device: Failed to open device: Operation not permitted (os error 1)
2024-11-12T10:25:22.094936Z  INFO niri: listening on Wayland socket: wayland-2
2024-11-12T10:25:22.094945Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-2.28255.sock
Error: nu::shell::core_dumped
```

**System Information:**

* Niri version: Built from main branch
* Distro: [Ubuntu 24.10 "Concept"](https://discourse.ubuntu.com/t/ubuntu-24-10-concept-snapdragon-x-elite/48800)
* Device: Leneovo T14s Gen 6 (Qualcom)
* GPU: Adreno (from the `dmesg` output)
* CPU: Snapdragon X Elite X1E-78-100 Processor (3.40 GHz)

**Additional Information:**

I have checked the kernel logs and found the following relevant output:

```
[    0.115465] [drm] Initialized simpledrm 1.0.0 for simple-framebuffer.0 on minor 0
[    0.116344] simple-framebuffer simple-framebuffer.0: [drm] fb0: simpledrmdrmfb frame buffer device
[    7.221417] systemd[1]: Starting modprobe@drm.service - Load Kernel Module drm...
[    7.226594] systemd[1]: modprobe@drm.service: Deactivated successfully.
[    7.226696] systemd[1]: Finished modprobe@drm.service - Load Kernel Module drm.
[    7.767071] WARNING: CPU: 4 PID: 92 at drivers/gpu/drm/panel/panel-edp.c:814 generic_edp_panel_probe+0x144/0x298
[    7.767082] Modules linked in: fastrpc(+) qrtr_smd rpmsg_ctrl qcom_pd_mapper ucsi_glink typec_ucsi qcom_battmgr snd_soc_lpass_rx_macro snd_soc_lpass_tx_macro snd_soc_lpass_wsa_macro snd_soc_lpass_va_macro aes_ce_blk snd_soc_lpass_macro_common aes_ce_cipher hci_uart crct10dif_ce btqca poly
```

FIY, I also could not start comsic, maybe for similar reasons.
Could this be a problem with freedreno or drm? 

This is the output of `ls -l /dev/dri`
|name|
|-|
|/dev/dri/by-path|
|/dev/dri/renderD128|
|/dev/dri/card1|

**Comment by YaLTeR** [comment]
Hmm. Yeah, can't really say what the problem is here, I don't have much experience with ARM.

> FIY, I also could not start comsic, maybe for similar reasons.

In this case I suggest opening an issue at cosmic-comp or Smithay, where there are more experienced developers who might be able to figure it out? Once it works in cosmic-comp I can see what I can do on the niri side.

**Comment by kenvandine** [comment]
I had an issue with cosmic-comp crashing on start on my X Elite device and worked around it with a feature flag for rustix. We added "use-libc" which seemed to do the trick for cosmic-comp.

**Comment by contra-bit** [comment]
> I had an issue with cosmic-comp crashing on start on my X Elite device and worked around it with a feature flag for rustix. We added "use-libc" which seemed to do the trick for cosmic-comp.

Thanks @kenvandine this has fixed all of the issues. 

Should I open an issue in rustix?

**Comment by kenvandine** [comment]
Yes, that would be ideal. Much appreciated!

**Comment by YaLTeR** [comment]
Oh, nice, thanks.

**Comment by hepek** [comment]
Here's the backtrace I am getting on Snapdragon Elite X

```
Thread 1 "niri" received signal SIGSEGV, Segmentation fault.
init_from_sysinfo_ehdr () at src/backend/linux_raw/vdso.rs:187
187	        vdso.nbucket = *hash.add(0);
(gdb) bt
#0  init_from_sysinfo_ehdr () at src/backend/linux_raw/vdso.rs:187
#1  new () at src/backend/linux_raw/vdso.rs:204
#2  init () at src/backend/linux_raw/vdso_wrappers.rs:488
#3  init_clock_gettime () at src/backend/linux_raw/vdso_wrappers.rs:285
#4  0x0000aaaaaae8d4bc in clock_gettime ()
    at /home/milan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.42/src/backend/linux_raw/vdso_wrappers.rs:65
#5  clock_gettime ()
    at /home/milan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.42/src/time/clock.rs:61
#6  get_monotonic_time () at src/utils/mod.rs:90
#7  call_once<fn() -> core::time::Duration, ()> ()
    at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/ops/function.rs:250
#8  get_or_insert_with<core::time::Duration, fn() -> core::time::Duration> ()
    at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/option.rs:1690
#9  now () at src/animation/clock.rs:103
#10 new () at src/animation/clock.rs:109
#11 default () at src/animation/clock.rs:159
#12 default<niri::animation::clock::AdjustableClock> ()
    at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/cell.rs:1320
#13 default<core::cell::RefCell<niri::animation::clock::AdjustableClock>> ()
    at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/rc.rs:2311
#14 default () at src/animation/clock.rs:13
#15 new () at src/niri.rs:1744
#16 0x0000aaaaaae822f8 in new () at src/niri.rs:565
#17 0x0000aaaaab264fe0 in main () at src/main.rs:174
#18 0x0000aaaaab280cec in call_once<fn() -> core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>, ()> ()
    at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/ops/function.rs:250
#19 __rust_begin_short_backtrace<fn() -> core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>, core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>> ()
    at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/backtrace.rs:154
#20 0x0000aaaaab297168 in std::rt::lang_start::{{closure}} () at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/rt.rs:195
#21 0x0000aaaaab5cec04 in core::ops::function::impls::{impl#2}::call_once<(), (dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> () at core/src/ops/function.rs:284
#22 std::panicking::try::do_call<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> ()
    at std/src/panicking.rs:557
#23 std::panicking::try<i32, &(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> ()
    at std/src/panicking.rs:520
#24 std::panic::catch_unwind<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> ()
    at std/src/panic.rs:358
#25 std::rt::lang_start_internal::{closure#1} () at std/src/rt.rs:174
#26 std::panicking::try::do_call<std::rt::lang_start_internal::{closure_env#1}, isize> () at std/src/panicking.rs:557
#27 std::panicking::try<isize, std::rt::lang_start_internal::{closure_env#1}> () at std/src/panicking.rs:520
#28 std::panic::catch_unwind<std::rt::lang_start_internal::{closure_env#1}, isize> () at std/src/panic.rs:358
#29 std::rt::lang_start_internal () at std/src/rt.rs:174
#30 0x0000aaaaab26abd8 in main ()
```

on 
`Linux  6.12.0-22-qcom-x1e #22-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan  8 15:22:58 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux`

with niri built from master:
```
./target/release/niri --version
niri 0.1.10 (v0.1.10-194-g89678c7b)
```

**Comment by YaLTeR** [comment]
It's a rustix issue caused by a change in the kernel. Update niri to the latest commit, it should have rustix with a hotfix.

**Comment by hepek** [comment]
I can confirm the issue is fixed with latest commit d574341f1f00dfeb7bedbd592d53f62e2911752d.

I guess I started debugging prematurely.

**Comment by YaLTeR** [comment]
Thanks for confirming! This is the first confirmation I received that the rustix hotfix indeed works; good to know.

**Comment by bakageddy** [comment]
I have the same issues
